### ISSUE TITLE
Error for maximum context length

### ISSUE THREAD

**Issue by savannahostrowski** [savannahostrowski/ghost#14]
![image](https://github.com/savannahostrowski/ghost/assets/8949415/1a8e7189-93b2-4ce8-b135-0de8d9f9d15c)

Ran into it when running Ghost over: https://github.com/savannahostrowski/ghost-vscode

**Comment by tomekz** [comment]
Hey, I've submitted PR with the fix.

**Comment by savannahostrowski** [comment]
Closed with #16
